baseURL = "https://mukilan.xyz/"
languageCode = "en-us"
title = "Mukilan.xyz"
<<<<<<< HEAD
publishDir = "docs"
=======
>>>>>>> ac9bfd88c98e3a85b0f06a9bdfa025ba35e21356

[params]
  description = "Hi there fellow traveller!"
  author = "Mukilan"

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
