baseURL = "https://mukilan.xyz/"
languageCode = "en-us"
title = "Mukilan.xyz"
relativeURLs = true

[params]
  description = "Hi there fellow traveller!"
  author = "Mukilan"

[[menus.main]]
  name = "home"
  url = "/"
  weight = 1

[[menus.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[menus.main]]
  name = "about"
  url = "/about/"
  weight = 3

[markup.goldmark.renderer]
  unsafe = true
